"""
Central configuration for EIAP (Enterprise AI Investment Analyst Platform).

All values are overridable via environment variables / a .env file
(see .env.example). Nothing sensitive is hard-coded.
"""
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # --- App ---
    APP_NAME: str = "Enterprise AI Investment Analyst Platform (EIAP)"
    ENV: str = "development"

    # --- Database ---
    DATABASE_URL: str = "sqlite:///./eiap.db"

    # --- Chunking (per PRD Section 4.1) ---
    CHUNK_SIZE_TOKENS: int = 800
    CHUNK_OVERLAP_TOKENS: int = 100

    # --- Retrieval ---
    RETRIEVAL_TOP_K_DENSE: int = 8
    RETRIEVAL_TOP_K_BM25: int = 4
    RETRIEVAL_FINAL_TOP_K: int = 5
    # Confidence threshold below which the system refuses to answer
    # rather than generate from a weak match (PRD Section 4.3, item 4).
    CONFIDENCE_THRESHOLD: float = 0.75

    # --- LLM synthesis ---
    # Provider is pluggable. "mock" works fully offline with no API key
    # and is the safe default; swap to "anthropic" or "openai" and set
    # the matching API key env var to get real generation.
    LLM_PROVIDER: str = "mock"  # "mock" | "anthropic" | "openai"
    LLM_MODEL: str = "claude-sonnet-4-6"
    ANTHROPIC_API_KEY: str = ""
    OPENAI_API_KEY: str = ""

    # --- Live market data (PRD Section 4.2) ---
    # No live vendor is wired up out of the box (that requires a paid
    # NSE/BSE/Tickertape/Screener API key). MARKET_DATA_PROVIDER "mock"
    # returns clearly-labeled placeholder data so the freshness-timestamp
    # and live-vs-filed disambiguation UX can still be demoed end-to-end.
    MARKET_DATA_PROVIDER: str = "mock"  # "mock" | "nse" | "tickertape"
    MARKET_DATA_API_KEY: str = ""

    # --- SEBI compliance disclosure template ---
    AUTOMATED_DISCLOSURE_TEMPLATE: str = (
        "SEBI Research Analyst Disclosure: This response was generated by "
        "{analyst_name} (SEBI Registration No. {sebi_reg_no}). Analyst "
        "{has_interest_disclosing_statement} have a financial interest in "
        "the securities discussed. This tool retrieves and summarizes "
        "information from public filings only. It is NOT investment advice "
        "and is not a substitute for a SEBI-registered Research Analyst or "
        "Investment Adviser. No buy/sell/hold recommendation is implied or "
        "provided."
    )


settings = Settings()
